---@class AbyssOptions
--The colorscheme options
---@field italic_comments boolean?
--Enables italic comments on colorscheme.
---@field italic boolean?
--Enables italic on colorscheme.
---@field bold boolean?
--Enables bold on colorscheme.
---@field transparent_background boolean?
--Enables transparent background on colorscheme.
