name: Tests
run-name: Abyss.nvim tests

on:
  pull_request:
    paths-ignore:
      - "**.md"
    branches: ["main", "develop"]
  push:
    paths-ignore:
      - "**.md"
    branches: ["main", "develop"]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        uses: MunifTanjim/setup-neovim-action@v1
        with:
          tag: nightly

      - name: Install plenary
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim test/plenary

      - name: Run tests
        run: |
          nvim --version
          [ ! -d test ] && exit 0
          nvim --headless --noplugin -u test/minimal_init.vim -c "PlenaryBustedDirectory ./test/abyss { minimal_init = './test/minimal_init.vim', sequential = true}"
